#!/bin/sh

mkdir $1
virtualenv-2.6 $1
cd $1
bin/easy_install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://dist.aclark.net/build/django/1.3.x/buildout.cfg
EOF
bin/buildout
