#!/bin/sh

mkdir $1
virtualenv-2.6 $1
cd $1
bin/easy_install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://pythonpackages.com/buildout/django/1.4.x
EOF
bin/buildout
bin/django runserver
