#!/bin/sh

if ! [ -n "$1" ]
then
    echo "Usage:\n\n$0 <dir>\n" 1>&2
    exit 1
fi
if ! [ -d $1 ]
then
    mkdir $1
fi
cd $1
virtualenv-2.7 $1
cd $1
bin/easy_install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://pythonpackages.com/buildout/django/1.4.x
EOF
bin/buildout
bin/django runserver
