#!/bin/sh

mkdir $1
virtualenv-2.7 $1
cd $1
bin/pip install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://build.pythonpackages.com/plone/4.2.x
EOF
bin/buildout
bin/paster serve plone.ini
