#!/bin/sh

mkdir $1
virtualenv-2.7 $1
cd $1
bin/pip install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://build.pythonpackages.com/buildout/apache/2.2.x
EOF
bin/buildout
bin/supervisord -e debug -n
