#!/bin/sh

mkdir $1
cd $1
virtualenv-2.7 .
bin/pip install zc.buildout
bin/buildout init
cat << EOF > buildout.cfg
[buildout]
extends = http://build.pythonpackages.com/buildout/plone/4.2.x-dev
EOF
bin/buildout
bin/plone fg
